name: Auto approval

on: [deployment, workflow_dispatch]

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Deploys
        uses: activescott/automate-environment-deployment-approval@v1.0.6
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_AUTO_APPROVING_DEPLOYS }}
          environment_allow_list: |
            D2
            P1
          actor_allow_list: |
            dependabot[bot]
            manish4deloitte
